# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:

  filelog:
    include: [/etc/otelcol-contrib/simple.log]
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'
        severity:
          parse_from: attributes.sev


processors:
  batch:

exporters:
  logging:
    verbosity: detailed

  prometheusremotewrite:
    endpoint: http://10.132.143.56:9090/api/v1/write
    headers:
      Authorization: "Basic YWRtaW46cGFzc3dvcmQ="

  zipkin:
    endpoint: http://10.132.143.56:9411/api/v2/spans

  elasticsearch/8:
    endpoints: https://10.132.143.56:9200
    traces_index: otel-traces
    logs_index: otel-logs
    user: elastic
    password: "61GFTVqG3YVZc=ad93Zi"
    tls:
      insecure: false
      insecure_skip_verify: true
      ca_file: /etc/otelcol-contrib/http_ca.crt



#  elasticsearch/8:
#    endpoints: https://10.132.143.56:9200
#    logs_index: otel-logs
#    username: elastic
#    password: 61GFTVqG3YVZc=ad93Zi
#    tls:
#      insecure: false
#      ca_file: /etc/otelcol-contrib/http_ca.crt
#    traces_index: otel-traces
#    sending_queue:
#      enabled: true
#      num_consumers: 20
#      queue_size: 1000

#  otlp/tempo:
#    endpoint: http://10.132.143.35:4320
#    tls:
#      insecure: false
#      ca_file: /etc/otelcol-contrib/tempo.crt

service:

  pipelines:

#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp/tempo, zipkin]

#    metrics:
#      receivers: [otlp, opencensus, prometheus]
#      processors: [batch]
#      exporters: [prometheusremotewrite]

    logs:
      receivers: [filelog, otlp]
      processors: [batch]
      exporters: [elasticsearch/8, logging]

  extensions: [health_check, pprof, zpages]
